// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WhereIsPogsTrain.Models;
//
//    var getRailwayNetworkDetail = GetRailwayNetworkDetail.FromJson(jsonString);

namespace WhereIsPogsTrain.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class GetRailwayNetworkDetail
    {
        [JsonProperty("code")]
        public long Code { get; set; }

        [JsonProperty("msg")]
        public string Msg { get; set; }

        [JsonProperty("data")]
        public List<Datum> Data { get; set; }
    }

    public partial class Datum
    {
        [JsonProperty("sequence")]
        public long Sequence { get; set; }

        [JsonProperty("lineName")]
        public string LineName { get; set; }

        [JsonProperty("lineNameZh")]
        public string LineNameZh { get; set; }

        [JsonProperty("lineNameEn")]
        public string LineNameEn { get; set; }

        [JsonProperty("lineNo")]
        public string LineNo { get; set; }

        [JsonProperty("lineColor")]
        public string LineColor { get; set; }

        [JsonProperty("subLine")]
        public List<SubLine> SubLine { get; set; }
    }

    public partial class SubLine
    {
        [JsonProperty("lineNameEn")]
        public string LineNameEn { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("direction")]
        public string Direction { get; set; }

        [JsonProperty("color")]
        public string Color { get; set; }

        [JsonProperty("trainIcon")]
        public Uri TrainIcon { get; set; }

        [JsonProperty("themeTrainIcon")]
        public Uri ThemeTrainIcon { get; set; }

        [JsonProperty("lineSequence")]
        public long LineSequence { get; set; }

        [JsonProperty("stationList")]
        public List<StationList> StationList { get; set; }
    }

    public partial class StationList
    {
        [JsonProperty("stationNo")]
        public string StationNo { get; set; }

        [JsonProperty("stationName")]
        public string StationName { get; set; }

        [JsonProperty("stationNameEn")]
        public string StationNameEn { get; set; }

        [JsonProperty("stationCode")]
        public string StationCode { get; set; }

        [JsonProperty("transferLines")]
        public string TransferLines { get; set; }

        [JsonProperty("startTime")]
        public string StartTime { get; set; }

        [JsonProperty("endTime")]
        public string EndTime { get; set; }

        [JsonProperty("sequence")]
        public long Sequence { get; set; }

        [JsonProperty("stationNameZh")]
        public string StationNameZh { get; set; }

        [JsonProperty("stationCodes")]
        public List<StationCode> StationCodes { get; set; }
    }
    /*
    public partial class StationCode
    {
        [JsonProperty("lineNo")]
        public string LineNo { get; set; }

        [JsonProperty("stationCode")]
        public string StationCodeStationCode { get; set; }
    }*/

    public partial class GetRailwayNetworkDetail
    {
        public static GetRailwayNetworkDetail FromJson(string json) => JsonConvert.DeserializeObject<GetRailwayNetworkDetail>(json, WhereIsPogsTrain.Models.Converter.Settings);
    }
}

