// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WhereIsPogsTrain.Models;
//
//    var getStationDistance = GetStationDistance.FromJson(jsonString);

namespace WhereIsPogsTrain.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class GetStationDistance
    {
        [JsonProperty("code")]
        public long Code { get; set; }

        [JsonProperty("msg")]
        public string Msg { get; set; }

        [JsonProperty("data")]
        public List<GetStationDistanceDatum> Data { get; set; }
    }

    public partial class GetStationDistanceDatum
    {
        [JsonProperty("lineNo")]
        public string LineNo { get; set; }

        [JsonProperty("startStation")]
        public string StartStation { get; set; }

        [JsonProperty("endStation")]
        public string EndStation { get; set; }

        [JsonProperty("distance")]
        public long Distance { get; set; }
    }

    public partial class GetStationDistance
    {
        public static GetStationDistance FromJson(string json) => JsonConvert.DeserializeObject<GetStationDistance>(json, WhereIsPogsTrain.Models.Converter.Settings);
    }

}
